services:
  - type: web
    name: kakao-share
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 9005
      - key: PORT
        value: 9005
      - key: PORT
        value: 9005
      - key: PORT
        value: 9005
      - key: PORT
        value: 9005
      - key: PORT
        value: 9005